### ISSUE TITLE
Options to Share Page

### ISSUE THREAD

**Issue by ProfoundWanderer** [danielgrijalva/overworld#136]
Currently, on game pages, the share link/button doesn't do anything.

Here is the share button currently:
![current](https://user-images.githubusercontent.com/18703678/62501810-0c4dd580-b7b2-11e9-9982-2a2839fc8aac.gif)

Not exactly sure what share options you would prefer. 

I did the below to try out an option for it:
![share](https://user-images.githubusercontent.com/18703678/62501251-92b4e800-b7af-11e9-9828-e5046a0dba38.gif)

Any idea what you want from the share option? e.g. what options to share to, functionality, etc.

**Comment by danielgrijalva** [comment]
Hey @ProfoundWanderer sorry for the delay. This looks really awesome! The only thing I'd add is an option to share (copy) the URL itself, for example:  
> ![Peek 2019-08-12 13-45](https://user-images.githubusercontent.com/11547406/62897158-7eb93b00-bd07-11e9-83c4-1dd4ef703562.gif)

**Comment by ProfoundWanderer** [comment]
Starting to work on this now. I had some weird issues with my project that I had to fix but everything seems to be working normally now.

**Comment by imdoingotherthings** [comment]
Interesting feature. I'd like to help out on this if no one is currently working on it.

**Comment by danielgrijalva** [comment]
Sure @imdoingotherthings go ahead!

**Comment by ProfoundWanderer** [comment]
@imdoingotherthings I haven't had time to work on it but if you look at my repo I do have it at the point will if you hover it the icons and url show (not a shortened url). It may give you a good starting spot.

**Comment by imdoingotherthings** [comment]
Nice! I'll take a look at it. Thanks! @danielgrijalva @ProfoundWanderer

**Comment by imdoingotherthings** [comment]
@ProfoundWanderer @danielgrijalva I'm receiving a 404 error from the backend. Any ideas?
So the reason why I'm starting up the server is because I'm receiving 404 errors on the frontend retrieving the data.

I've installed all dependencies and packages from Django, Python3 and React respectively using the `.sh` file and `requirements.txt` file.

The issue that I'm currently receiving from both **http://localhost:8000/** and **http://127.0.0.1:8000/** is this: 

_Not Found
The requested resource was not found on this server._

I've also tested both frontend and backend endpoints using postman, receiving the same 404 error.
(i.e.  `/api/games/popular`) given that axios is still listening for **http://localhost:8000/**.

I'm using `python3 manage.py runserver` to run the django server.

**Comment by ProfoundWanderer** [comment]
Not that I know of but give me like 2 hours and I'll make sure the latest
was pushed.

**Comment by ProfoundWanderer** [comment]
It's the most updated but the only thing I can think of is make sure your
api key is good and not over the limit of calls.

**Comment by imdoingotherthings** [comment]
This is probably the issue. I haven't injected my api key. I'll give that a shot. Thanks! @ProfoundWanderer

**Comment by danielgrijalva** [comment]
@imdoingotherthings any updates? 😮

**Comment by nobi1007** [comment]
Hey @danielgrijalva can I work on this issue, if yes, please let me know what url-shortener you would suggest !

**Comment by nobi1007** [comment]
This is how it looks if the **PR** is merged,

![improve_share_option](https://user-images.githubusercontent.com/30571441/89061561-8a6f9880-d382-11ea-9d4f-a817a794ae1f.gif)

**Comment by danielgrijalva** [comment]
@nobi1007 amazing! thank you, will merge now
