### ISSUE TITLE
Possible legal issues

### ISSUE THREAD

**Issue by andrhua** [danielgrijalva/overworld#140]
I don't mind the fact that nowadays a lot of stuff is coming, so to speak, from others ideas, but this one really bothers me. I think at least you should think of different UI, because who knows how greedy the Letterboxd guys are. I'm not affiliated with them, just speaking from stranger's perspective

**Comment by danielgrijalva** [comment]
I hear you. I was a bit concerned about this too, but since we haven’t really stolen/copied any code directly from them, I doubt there would be any legal problems. 

The only issue would be that the design/layout is extremely similar, but still, we are _not_ monetizing through ads or anything so they are not being hurt with this 🤷‍♂

Lastly, they are a small team from New Zealand with 1.5+ million users so… I don’t think they are greedy at all 😅 

Still, in the future I would like to personally contact them to let them know about this project and get their consent.
