### ISSUE TITLE
Refactor Frontend to use Functional Components

### ISSUE THREAD

**Issue by RodPaDev** [danielgrijalva/overworld#156]
I've been taking a look at the frontend part of this project and noticed that most of the components are written used class components, which in itself is not bad but functional components are faster and don't have all that componentWillDid nonsense

To proceed with this I would first write test for each component and then proceed on to refactoring into functional

I know refactoring is scary but I believe it's do able. Also to note, this is my first try at contributing to an opensource project

**Comment by danielgrijalva** [comment]
Hello @rodpa715. I've been considering this for a few weeks now, since I've been reading about hooks and all that new stuff. It is scary indeed, but doable and the benefits are worth it. 

Your approach to this issue sounds excellent (write tests first) so, **go ahead**! 🎉 

The only problem is that there's little documentation for each front end component (I'm lacking of free time lately 😅). I'll try and write more docs but in the meantime don't be afraid to ask me stuff through. Thanks again!
